# Generated by Django 3.2 on 2022-01-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVideo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(verbose_name='Post a comment'),
        ),
        migrations.AlterField(
            model_name='streamvideo',
            name='videoURL',
            field=models.URLField(blank=True, null=True, verbose_name='Video url(Embed link only for youtube)'),
        ),
    ]
